Restauran/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('foods.urls')),
    path('', include('reservation.urls')),
    path('', include('blog.urls')),
    path('', include('menu.urls')),
    path('', include('about.urls')),
    path('', include('contact.urls')),
    path('', include('stuff.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog_list, blog_detail, blog_tag, blog_category, Search

app_name = "blogs"

urlpatterns = [
    path('blog/', blog_list),
    path('blog/<int:id>/', blog_detail, name="blog_detail"),
    path("blog/tag/<slug:tag>", blog_tag, name="tag"),
    path("blog/category/<slug:category>", blog_category, name="category"),
    path("blog/search", Search, name="search"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    title = models.CharField(blank=True, max_length=1000)
    descriptions = models.TextField(blank=True)
    content = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    first_image = models.ImageField(upload_to='blogs/', blank=True)
    second_image = models.ImageField(upload_to='blogs/', blank=True)
    category = models.ForeignKey("Category", on_delete=models.CASCADE, blank=True, null=True, related_name="blogs")
    tags = models.ManyToManyField("Tag", default=None, related_name="blogs", blank=True)

    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    published_at = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.CharField(max_length=50)
    published_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title


class Comments(models.Model):
    blog = models.ForeignKey("Blog", on_delete=models.CASCADE, related_name="comments")
    fullname = models.CharField(max_length=500)
    email = models.EmailField(blank=True)
    massage = models.TextField(blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.massage

blog/forms.py
from django import forms

class CommetForm(forms.Form):
    fullname = forms.CharField(max_length=500)
    email = forms.EmailField()
    massage = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.shortcuts import render
from .models import Blog, Tag, Category, Comments
from .forms import CommetForm

# Create your views here.

#==============================blog_list==============================#

def blog_list(request):
    blog_list = Blog.objects.all()

    context = {
        "blog_list": blog_list,
    }
    return render(request, "blogs/blog_list.html", context)

#==============================blog_detail==============================#

def blog_detail(request, id):
    blog = Blog.objects.get(id=id)
    tags = Tag.objects.all().filter(blogs=blog)
    recents = Blog.objects.all().order_by("-created_at")
    Categories = Category.objects.all()
    comments = Comments.objects.all().filter(blog=blog)

    if request.method == "POST":
        form = CommetForm(request.POST)
        if form.is_valid():
            fullname = form.cleaned_data["fullname"]
            email = form.cleaned_data["email"]
            massage = form.cleaned_data["massage"]
            new_comment = Comments(blog=blog, fullname=fullname, email=email, massage=massage)
            new_comment.save()

    context = {
        "blog": blog,
        "tags": tags,
        "recents": recents,
        "Categories": Categories,
        "comments": comments,
    }
    return render(request, "blogs/blog_detail.html", context)

#==============================blog_tag==============================#

def blog_tag(request,tag):
    blog_list = Blog.objects.filter(tags__slug=tag)
    context = {
        "blog_list": blog_list
    }
    return render(request, "blogs/blog_list.html", context)

#==============================blog_category==============================#

def blog_category(request, category):
    blog_list = Blog.objects.filter(category__slug=category)
    context = {
        "blog_list": blog_list
    }
    return render(request, "blogs/blog_list.html", context)

#==============================blog_Search==============================#

def Search(request):
    if request.method == "GET":
        q = request.GET.get("search")
    blog_list = Blog.objects.filter(title__icontains=q)
    context = {
        "blog_list": blog_list
    }
    return render(request, "blogs/blog_list.html", context)

blog/templates/blogs/blog_detail.html
{% extends 'shared/_Main.html' %}
{% load static %}
{% block Content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>{{ blog.title }}</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->

	<!-- Start blog details -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>{{ blog.title }}</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-8 col-lg-8 col-12">
					<div class="blog-inner-details-page">
						<div class="blog-inner-box">
							<div class="side-blog-img">
								<img class="img-fluid" src="{{ blog.second_image.url }}" alt="">
								<div class="date-blog-up">
                                    {{ blog.created_at | date:"y b d" }}
								</div>
							</div>
							<div class="inner-blog-detail details-page">
								<h3>{{ blog.title }}</h3>
								<ul>
									<li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ blog.author }}</span></li>
									<li>|</li>
									<li><i class="zmdi zmdi-time"></i>Time : <span>{{ blog.created_at.time }}</span></li>
								</ul>
								<p>{{ blog.content }}</p>
								<blockquote>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non feugiat lacus. Nunc nisi velit, consectetur vitae ex porttitor, placerat scelerisque mauris. Phasellus sit amet tincidunt metus, quis tempus ex. Quisque in lorem ut mi ullamcorper suscipit eu nec purus. Nam maximus sagittis iaculis.</p>
								</blockquote>
								<p>{{ blog.descriptions }}</p>
							</div>
						</div>
						<div class="blog-comment-box">
							<h3>Comments</h3>
							{% for comment in comments %}
                                <div class="comment-item">
								<div class="comment-item-left">
									<img src="{% static 'images/avt-img.jpg' %}" alt="">
								</div>
								<div class="comment-item-right">
									<div class="pull-left">
										<a href="{% url 'blogs:blog_detail' blog.id %}">{{ comment.fullname }}</a>
									</div>
									<div class="pull-right">
										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>{{ comment.date | date }}</span>
									</div>
									<div class="des-l">
										<p>{{ comment.massage }}</p>
									</div>
{#									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>#}
								</div>
							</div>
							{% endfor %}

{#							<div class="comment-item children">#}
{#								<div class="comment-item-left">#}
{#									<img src="{% static 'images/avt-img.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="comment-item-right">#}
{#									<div class="pull-left">#}
{#										<a href="#">Admin</a>#}
{#									</div>#}
{#									<div class="pull-right">#}
{#										<i class="fa fa-clock-o" aria-hidden="true"></i>Time : <span>1.30 pm</span>#}
{#									</div>#}
{#									<div class="des-l">#}
{#										<p>Morbi lacinia ultrices lorem id tincidunt. Cras id dui risus. Pellentesque consectetur id mi sed pharetra. Proin imperdiet gravida nisl, sit amet varius urna. In auctor.</p>#}
{#									</div>#}
{#									<a href="#" class="right-btn-re"><i class="fa fa-reply" aria-hidden="true"></i> Reply</a>#}
{#								</div>#}
{#							</div>#}
						</div>
						<div class="comment-respond-box">
							<h3>Leave your comment </h3>
							<div class="comment-respond-form">
								<form id="commentrespondform" class="comment-form-respond row" method="post">
                                    {% csrf_token %}
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
											<input id="name_com" class="form-control" name="fullname" placeholder="Name" type="text">
										</div>
										<div class="form-group">
											<input id="email_com" class="form-control" name="email" placeholder="Your Email" type="email">
										</div>
									</div>
									<div class="col-lg-6 col-md-6 col-sm-6">
										<div class="form-group">
                                            <textarea class="form-control" name="massage" id="textarea_com"  placeholder="Your Message" rows="2"></textarea>
										</div>
									</div>
									<div class="col-lg-12 col-md-12 col-sm-12">
										<button class="btn btn-submit">Submit comment</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xl-4 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
					<div class="right-side-blog">
						<h3>Search</h3>
                        <form method="GET" action="{% url 'blogs:search' %}">
                            <div class="blog-search-form">
                                <input name="search" placeholder="Search blog" type="text">
                                <button class="search-btn" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                            </div>
                        </form>
						<h3>Categories</h3>
						<div class="blog-categories">
							<ul>
                                {% for Category in Categories %}
                                    <li><a href="{% url 'blogs:category' Category.slug %}"><span>{{ Category.title }}</span></a></li>
                                {% endfor %}
							</ul>
						</div>
						<h3>Recent Post</h3>
						<div class="post-box-blog">
							<div class="recent-post-box">
								{% for blog in recents %}
                                    <div class="recent-box-blog">
                                        <div class="recent-img">
                                            <img class="img-fluid" src="{{ blog.second_image.url }}" alt="" style="height: 100px; width: 100px">
                                        </div>
                                        <div class="recent-info">
                                            <ul>

                                                <li><i class="zmdi zmdi-account"></i>Posted By : <span>{{ blog.author }}</span></li>

                                                <li>|</li>

                                                <li><i class="zmdi zmdi-time"></i>Time : <span>{{ blog.created_at | time }}</span></li>

                                            </ul>
                                            <h4>Duis feugiat neque sed dolor cursus, sed lacinia nisl pretium.</h4>
                                        </div>
                                    </div>
                                {% endfor %}
							</div>
						</div>
						<h3>Recent Tag</h3>
						<div class="blog-tag-box">
							<ul class="list-inline tag-list">
								{% for tag in tags %}
								<li class="list-inline-item"><a href="{% url 'blogs:tag' tag.slug %}">{{ tag.title }}</a></li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- End details -->
{% endblock %}

blog/templates/blogs/blog_list.html
{% extends 'shared/_Main.html' %}
{% load static %}
{% block Content %}
	<!-- Start All Pages -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>Blog</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End All Pages -->

	<!-- Start blog -->
	<div class="blog-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="heading-title text-center">
						<h2>Blog</h2>
						<p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
					</div>
				</div>
			</div>
			<div class="row">
                {% for blog in blog_list %}
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="blog-box-inner">
                            <div class="blog-img-box">
                                <img class="img-fluid" src="{{ blog.first_image.url }}" alt="">
                            </div>
                            <div class="blog-detail">
                                <h4>{{ blog.title }}</h4>
                                <ul>
                                    <li><span>{{ blog.author }}</span></li>
                                    <li>|</li>
                                    <li><span>{{ blog.created_at | date:"y b d" }}</span></li>
                                </ul>
                                <p>{{ blog.descriptions }}</p>
                                <a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'blogs:blog_detail' blog.id %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
			</div>
		</div>
	</div>
	<!-- End blog -->

{% endblock %}